### ISSUE TITLE
Distribute py.typed file for mypy typings

### ISSUE THREAD

**Issue by cancan101** [anvilco/python-anvil#20]
See:
* https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
* https://mypy.readthedocs.io/en/stable/installed_packages.html#making-pep-561-compatible-packages
* https://www.python.org/dev/peps/pep-0561/#packaging-type-information

Otherwise you get:
```
xxx.py:11: error: Skipping analyzing "python_anvil.api": found module but no type hints or library stubs
xxx.py:11: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

**Comment by aalmazan** [comment]
Will be taking a look at this and will aim for the next release. Thanks for the feedback!
